### ISSUE TITLE
Option to disallow adding new and removing existing propertis to the observable

### ISSUE THREAD

**Issue by eubyte** [gullerya/object-observer#34]
It would be nice to have an option where the observable object is prevented from new properties being added , and existing properties being removed (similar behavior to Object.seal()  )

This will serve the use case where we only want to change/mutate the existing properties (e.g. application state managements, etc.).

Thank you!

**Comment by gullerya** [comment]
Hi,
I've just tried to actually do an `Object.seal` on observable and it works as expected, IMHO.
Specifically, if you'll run `Object.seal` on observable, then:
- no new properties may be added, TypeError thrown, as well as no existing properties may be deleted
- any existing properties are still subject to modification and any modification of those is correctly observed and notified to listeners

I've just pushed a set of tests to cover those cases, you may review the tests in `tests/module/test-object-generics.js` and notify me if I've missed anything.

If so - is it answer your case?

**Comment by eubyte** [comment]
Thank you! You are right, it does work as intended. I realized that our use case required deepSeal functionality.  We wrote a deepSeal() function and then did deepSeal(observable) -- everything seems to be fine now. Perhaps, building this functionality (and having an option to use it) in the core of the library is still not such a bad idea.

Thank you again for you great work!

**Comment by gullerya** [comment]
Must say that my inclination is to keep the `object-observer` focused on it's own concern - observation, and not extend it with less specific and more object-utilities-like functionalities.

Anyway, glad it worked out well for you and thanks for the feedback!
